"""empty message

Revision ID: 3e724db9fa5e
Revises: 
Create Date: 2019-03-29 11:58:48.637503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e724db9fa5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=75), nullable=True),
    sa.Column('description', sa.String(length=75), nullable=True),
    sa.Column('client', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature')
    # ### end Alembic commands ###
