version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: ng02
    links:
      - web
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./conf/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    image: realmonchi/iwsfeatureapp:v3
    expose:
      - "8000"
    environment:
      - SECRET_KEY= 'changemeinprod'
