version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: ng02
    ports:
      - "80:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    image: realmonchi/iwsfeatureapp:v2
    expose:
      - "8000"
    environment:
      - SECRET_KEY = 'changemeinprod"
