version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: ng02
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
    depends_on:
      - web
    network_mode: "host"

  web:
    network_mode: "host"
    image: realmonchi/iwsfeatureapp:v9
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY = 'changemeinprod'
