version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: ng05
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
    network_mode: "host"
  web:
    image: realmonchi/iwsfeatureapp:v24
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY= 'changemeinprod'
    network_mode: "host"
