version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng05
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - ./app/static:/static
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
      - db
    network_mode: "host"
  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER = 'victor'
      - POSTGRES_PASSWORD= 'test123'
      - POSTGRES_DB= 'features'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/postgresql/data
    network_mode: "host"
  web:
    build: app
    command: ['./wait-for-postgres.sh']
    restart: always
    volumes:
      - ./logs/web:/var/log/gunicorn
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY= 'changemeinprod'
    network_mode: "host"
    depends_on:
      - db
